# Development environment configuration
# Inherits from base.yml and overrides specific values

data_generation:
  default_records: 100  # Smaller dataset for faster development iteration
  
logging:
  level: "DEBUG"