# Production environment configuration
# Inherits from base.yml and overrides specific values

data_generation:
  default_records: 100000  # Larger dataset for production demos

logging:
  level: "WARNING"