# Base configuration with default values for local data generation
# These can be overridden by environment-specific configs or environment variables

data_generation:
  default_records: 1000

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Application settings
app:
  name: "sales-demo"
  version: "0.1.0"